#!/usr/bin/env bash
# This program is part of Aspersa (http://code.google.com/p/aspersa/)

# ########################################################################
# This script aggregates GDB stack traces for a selected program.  By default it
# does mysqld.
#
# Author: Baron Schwartz, based on a script by Domas Mituzas at
# poormansprofiler.org
# ########################################################################

# License: BSD 3-clause
# https://opensource.org/licenses/BSD-3-Clause

# Print a usage message and exit.
usage() {
   if [ "${OPT_ERR}" ]; then
      echo "${OPT_ERR}"
   fi
   cat <<-USAGE
Usage: $0 [OPTIONS] [FILE]
   $0 does two things: 1) get a GDB backtrace 2) aggregate it.
   If you specify a FILE, then step 1) is not performed.
Options:
   -b BINARY      Which binary to trace (default mysqld)
   -i ITERATIONS  How many traces to gather and aggregate (default 10)
   -k KEEPFILE    Keep the raw traces in this file after aggregation
   -l NUMBER      Aggregate only first NUMBER functions; 0=infinity (default 16)
   -p PID         Process ID of the process to trace; overrides -b
   -s SLEEPTIME   Number of seconds to sleep between iterations (default 0)
   -t THREAD      Threads to trace (default all)
   --no-demangle  Do not demangle OCaml functions, print raw symbol names
	USAGE
   exit 1
}

# Actually does the aggregation.  The arguments are the max number of functions
# to aggregate, and the files to read.  If maxlen=0, it means infinity.  We have
# to pass the maxlen argument into this function to make maxlen testable.
aggregate_stacktrace() {
   maxlen="$1";
   demangle="$3";
   cat > ${tmpfile}.awk <<EOF
      BEGIN {
         s = "";
      }
      /^Thread/ {
         if ( s != "" ) {
            print s;
         }
         s = "";
         c = 0;
      }
      /^\#/ {
         if ( \$2 ~ /0x/ ) {
            if ( \$4 ~/ (void|const) / ) {
               targ = \$5;
            }
            else {
               targ = \$4;
            }
         }
         else {
            targ = \$2;
         }
         if ( targ ~ /[<\\(]/ && targ !~ /^operator[<\\(]/ ) {
            if ( \$2 ~ /0x/ ) {
              targ = substr(\$0, index(\$0, " in ") + 4); # skip "#XX 0xADDR in"
            }
            else {
              targ = substr(\$0, 4); // skip #XX
            }
            if ( targ ~ / from / ) {
               targ = substr(targ, 1, index(targ, " from ") - 1);
            }
            if ( targ ~ / at / ) {
               targ = substr(targ, 1, index(targ, " at ") - 1);
            }
            # Further shorten argument lists.
            while ( targ ~ /\\(/ ) {
               if ( 0 == gsub(/\\([^()]*\\)/, "", targ) ) {
                  break;
               }
            }
            # Shorten C++ templates, e.g. in t/samples/stacktrace-004.txt
            while ( targ ~ />( *\$|::)/ ) {
               if ( 0 == gsub(/<[^<>]*>/, "", targ) ) {
                  break;
               }
            }
            # Remove void and const decorators.
            gsub(/ (void|const) /, "", targ);
            gsub(/ /, "", targ);
         }
         else if ( targ ~ /\\?\\?/ && \$2 ~ /[1-9]/ ) {
            # Substitute ?? by the name of the library.
            targ = \$NF;
            while ( targ ~ /\\// ) {
               targ = substr(targ, index(targ, "/") + 1);
            }
            targ = substr(targ, 1, index(targ, ".") - 1);
            targ = targ "::??";
         }
         else if ( ${demangle} == 1 && targ ~ /^caml/ && targ !~ /^caml_/ ) {
           a = split(targ, p, "_");
           if (a > 1 && p[a] ~ /^[0-9]+$/)
           {
             if (p[a-1] == "fun")
             {
               targ = substr(targ, 1, length(targ) - length(p[a]) - length(p[a-1]) - 1) "#" p[a]
             }
             else
             {
               targ = substr(targ, 1, length(targ) - length(p[a]) - 1)
             }
           }
           gsub(/__/, ".", targ);
           sub(/^caml/, "", targ);
         }
         # get rid of long symbol names such as 'pthread_cond_wait@@GLIBC_2.3.2'
         if ( targ ~ /@@/ ) {
            fname = substr(targ, 1, index(targ, "@@") - 1);
         }
         else {
            fname = targ;
         }
         if ( ${maxlen:-0} == 0 || c < ${maxlen:-0} ) {
            if (s != "" ) {
               s = s " " fname;
            }
            else {
               s = fname;
            }
         }
         c++;
      }
      END {
         print s
      }
EOF
   awk -f ${tmpfile}.awk "$2" | sort | uniq -c | sort -n -k 1,1
}

# The main program to run.
main() {
   export tmpfile=$(tempfile --prefix=pmp);

   # Get command-line options
   for o; do
      case "${o}" in
         --)
            shift; break;
            ;;
         --help)
            usage;
            ;;
         -b)
            shift; OPT_b="${1}"; shift;
            ;;
         -i)
            shift; OPT_i="${1}"; shift;
            ;;
         -k)
            shift; OPT_k="${1}"; shift;
            ;;
         -l)
            shift; OPT_l="${1}"; shift;
            ;;
         -p)
            shift; OPT_p="${1}"; shift;
            ;;
         -s)
            shift; OPT_s="${1}"; shift;
            ;;
         -t)
            shift; OPT_t="${1}"; shift;
            ;;
         --no-demangle)
            shift; OPT_demangle=0;
            ;;
         -*)
            OPT_ERR="Unknown option ${o}."
            usage
            ;;
      esac
   done
   export OPT_i="${OPT_i:-10}";
   export OPT_k="${OPT_k:-}";
   export OPT_l="${OPT_l:-16}";
   export OPT_b="${OPT_b:-mysqld}";
   export OPT_p="${OPT_p:-}";
   export OPT_s="${OPT_s:-0}";
   export OPT_t="${OPT_t:-all}";
   export OPT_demangle="${OPT_demangle:-1}";

   if [ -z "${1}" ]; then
      # There's no file to analyze, so we'll make one.
      if [ -z "${OPT_p}" ]; then
         OPT_p=$(pidof -s "${OPT_b}" 2>/dev/null);
         if [ -z "${OPT_p}" ]; then
            OPT_p=$(pgrep -o -x "${OPT_b}" 2>/dev/null)
         fi
         if [ -z "${OPT_p}" ]; then
            OPT_p=$(ps -eaf | grep "${OPT_b}" | grep -v grep | awk '{print $2}' | head -n1);
         fi
      fi
      date;
      for x in $(seq 1 $OPT_i); do
         gdb -ex "set pagination 0" -ex "thread apply $OPT_t bt" -batch /proc/$OPT_p/exe -p $OPT_p >> "${OPT_k:-${tmpfile}}"
         date +'TS %N.%s %F %T' >> "${OPT_k:-${tmpfile}}"
         sleep $OPT_s
      done
   fi

   if [ $# -eq 0 ]; then
      aggregate_stacktrace "${OPT_l}" "${OPT_k:-${tmpfile}}" "${OPT_demangle}"
   else
      aggregate_stacktrace "${OPT_l}" "$@" "${OPT_demangle}"
   fi
   rm -f ${tmpfile} ${tmpfile}.awk
}

# Execute the program if it was not included from another file.  This makes it
# possible to include without executing, and thus test.
if [ "$(basename "$0")" = "pmp" ] || [ "$(basename "$0")" = "bash" -a "$_" = "$0" ]; then
    main "$@"
fi
